/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as proxySol from "./Proxy.sol";
export type { proxySol };
export type { Factory } from "./Factory";
export type { Lock } from "./Lock";
export type { LotteryNft } from "./LotteryNft";
export type { LotteryNftV2 } from "./LotteryNftV2";
export type { MetamorphicFactory } from "./MetamorphicFactory";
export type { Token } from "./Token";
